  name: MPPlugin
  main: fr.bastoup.mpplugin.MPPlugin
  version: 1.0-SNAPSHOT
  description: Plugin du serveur de la MP*1
  api-version: 1.17
  author: BastouP

  commands:
    shop:
      description: Gérer un shop.
      permission: mpplugin.shop
      permission-message: Vous n'avez pas la permission d'utiliser cette commande.
      usage: "/shop <create|remove> [nom] [prix]"
    bank:
      description: Gérer les banques.
      permission: mpplugin.bank
      permission-message: Vous n'avez pas la permission d'utiliser cette commande.
      usage: "/bank <create|remove> [nom] [prix]"
    money:
      description: Gérer les banques.
      permission: mpplugin.money
      permission-message: Vous n'avez pas la permission d'utiliser cette commande.
      usage: "/money <balance|transfer> [joueur] [montant]"
    spawn:
      description: Permet de revenir au spawn.
      permission: mpplugin.spawn
      permission-message: Vous n'avez pas la permission d'utiliser cette commande.
      usage: "/spawn"
    home:
      description: Permet de gérer sa maison.
      permission: mpplugin.home
      permission-message: Vous n'avez pas la permission d'utiliser cette commande.
      usage: "/home [set]"

  permissions:
    mpplugin.shop:
      description: Donne la permission d'utiliser /shop.
      default: true
    mpplugin.bank:
      description: Donne la permission d'utiliser /bank.
      default: op
    mpplugin.money:
      description: Donne la permission d'utiliser /money.
      default: true
    mpplugin.spawn:
      description: Donne la permission d'utiliser /spawn.
      default: true
    mpplugin.home:
      description: Donne la permission d'utiliser /home.
      default: true
    mpplugin.*:
      description: Donne la permission d'utiliser toutes les commandes.
      default: op
      children:
        mpplugin.shop: true
        mpplugin.bank: true
        mpplugin.money: true
        mpplugin.home: true
        mpplugin.spawn: true